from cvss_types import *

Metric = {
    Vector.NETWORK: 0.85,
    Vector.ADJACENT: 0.62,
    Vector.LOCAL: 0.55,
    Vector.PHYSICAL: 0.2,
    Complexity.LOW: 0.77,
    Complexity.HIGH: 0.44,
    Privileges.NONE: 0.85,
    Privileges.LOW: 0.62,
    Privileges.CH_LOW: 0.68,
    Privileges.HIGH: 0.27,
    Privileges.CH_HIGH: 0.5,
    Interaction.NONE: 0.85,
    Interaction.REQUIRED: 0.62,
    CIA.NONE: 0,
    CIA.LOW: 0.22,
    CIA.HIGH: 0.56,
    CIA.ND: 1,
    CIAR.LOW: 0.5,
    CIAR.MED: 1,
    CIAR.HIGH: 1.5,
    CIAR.ND: 1,
    Maturity.UNPROVEN: 0.91,
    Maturity.POC: 0.94,
    Maturity.FUNCTIONAL: 0.97,
    Maturity.HIGH: 1,
    Maturity.ND: 1,
    Remediation.OFFICIAL: 0.95,
    Remediation.TEMPORARY: 0.96,
    Remediation.WORKAROUND: 0.97,
    Remediation.UNAVAILABLE: 1,
    Remediation.ND: 1,
    Confidence.UNKNOWN: 0.95,
    Confidence.REASONABLE: 0.96,
    Confidence.CONFIRMED: 1,
    Confidence.ND: 1
}
